---
- name: installtion of software on widnows machine
  hosts: winsrv
  tasks:
   - name: Download apache on windows
     win_get_url:
       url: https://archive.apache.org/dist/httpd/binaries/win32/apache_2.0.36-win32-x86-no_ssl.msi
       dest: C:\ansible_example\apache_2.0.36-win32-x86-no_ssl.msi
   - name: Install MSI
     win_package:
       path: C:\ansible_example\apache_2.0.36-win32-x86-no_ssl.msi
       state: absent
     
