---
- name: installation of web server
  hosts: websrv
  tasks:
   - name: installed of web application server
     yum:
      name: httpd22
      state: present
     register: yum_output
     ignore_errors: true

   - name: show the value stored into register variable
     debug:
       msg: "{{ yum_output }}" 
